CREATE TABLE IF NOT EXISTS ospedale (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  regione VARCHAR(50) NOT NULL,
  provincia VARCHAR(50) NOT NULL
);

INSERT INTO ospedale (id, nome, regione, provincia)
VALUES
  (1, 'Ospedale San Giovanni', 'Lombardia', 'Milano'),
  (2, 'Ospedale Maggiore', 'Lombardia', 'Milano'),
  (3, 'Ospedale Fatebenefratelli', 'Lombardia', 'Milano'),
  (4, 'Ospedale Niguarda', 'Lombardia', 'Milano'),
  (5, 'Ospedale San Raffaele', 'Lombardia', 'Milano'),
  (6, 'Ospedale Policlinico di Milano', 'Lombardia', 'Milano'),
  (7, 'Ospedale Papa Giovanni XXIII', 'Lombardia', 'Bergamo'),
  (8, 'Ospedale di Circolo e Fondazione Macchi', 'Lombardia', 'Varese'),
  (9, 'Ospedale degli Infermi di Rimini', 'Emilia-Romagna', 'Rimini'),
  (10, 'Ospedale Bufalini', 'Emilia-Romagna', 'Cesena'),
  (11, 'Ospedale Maggiore di Parma', 'Emilia-Romagna', 'Parma'),
  (12, 'Ospedale Universitario di Modena', 'Emilia-Romagna', 'Modena'),
  (13, 'Ospedale Santa Maria della Scaletta', 'Emilia-Romagna', 'Imola'),
  (14, 'Ospedale Maggiore di Bologna', 'Emilia-Romagna', 'Bologna'),
  (15, 'Ospedale Sant%sOrsola-Malpighi', 'Emilia-Romagna', 'Bologna'),
  (16, 'Ospedale Bellaria-Maggiore', 'Emilia-Romagna', 'Bologna'),
  (17, 'Ospedale degli Infermi di Faenza', 'Emilia-Romagna', 'Faenza'),
  (18, 'Ospedale Maurizio Bufalini di Cesena', 'Emilia-Romagna', 'Cesena'),
  (19, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (20, 'Ospedale San Camillo-Forlanini', 'Lazio', 'Roma'),
  (21, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (22, 'Ospedale San Filippo Neri', 'Lazio', 'Roma'),
  (23, 'Ospedale Pediatrico Bambino Gesù', 'Lazio', 'Roma'),
  (24, 'Ospedale S. Eugenio', 'Lazio', 'Roma'),
  (25, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (26, 'Ospedale Sant%sEugenio', 'Lazio', 'Roma'),
  (27, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (28, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (29, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (30, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (31, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (32, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (33, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (34, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (35, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (36, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (37, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (38, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (39, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (40, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (41, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (42, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (43, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (44, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (45, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (46, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (47, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (48, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (49, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (50, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (51, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (52, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (53, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (54, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (55, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (56, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (57, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (58, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (59, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (60, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (61, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (62, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (63, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (64, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (65, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (66, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (67, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (68, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (69, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (70, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (71, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (72, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (73, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (74, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (75, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (76, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (77, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (78, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (79, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (80, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (81, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (82, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (83, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (84, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (85, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (86, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (87, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (88, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (89, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (90, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (91, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (92, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (93, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (94, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (95, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (96, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (97, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (98, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (99, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (100, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (101, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (102, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (103, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (104, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (105, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (106, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (107, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (108, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (109, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (110, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (111, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (112, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (113, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (114, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (115, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (116, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (117, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (118, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (119, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (120, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (121, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (122, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (123, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (124, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (125, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (126, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (127, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (128, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (129, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (130, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (131, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (132, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (133, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (134, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (135, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (136, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (137, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (138, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (139, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (140, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (141, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (142, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (143, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (144, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (145, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (146, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (147, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (148, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (149, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (150, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (151, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (152, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (153, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (154, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (155, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (156, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (157, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (158, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (159, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (160, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (161, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (162, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (163, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (164, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (165, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (166, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (167, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (168, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (169, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (170, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (171, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (172, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (173, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (174, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (175, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (176, 'Ospedale San Giovanni di Dio', 'Toscana', 'Firenze'),
  (177, 'Ospedale San Donato', 'Toscana', 'Arezzo'),
  (178, 'Ospedale Misericordia di Grosseto', 'Toscana', 'Grosseto'),
  (179, 'Ospedale di Prato', 'Toscana', 'Prato'),
  (180, 'Ospedale Sant%sAgostino Estense', 'Emilia-Romagna', 'Modena'),
  (181, 'Ospedale Guglielmo da Saliceto', 'Emilia-Romagna', 'Piacenza'),
  (182, 'Ospedale Civile di Mirandola', 'Emilia-Romagna', 'Modena'),
  (183, 'Ospedale Santa Maria delle Croci', 'Emilia-Romagna', 'Ravenna'),
  (184, 'Ospedale di Carpi', 'Emilia-Romagna', 'Modena'),
  (185, 'Ospedale Nuovo di Sassuolo', 'Emilia-Romagna', 'Modena'),
  (186, 'Ospedale Bufalini', 'Toscana', 'Cesena'),
  (187, 'Ospedale Umberto I', 'Toscana', 'Lucca'),
  (188, 'Ospedale Santa Maria della Scala', 'Toscana', 'Siena'),
  (189, 'Ospedale del Ceppo', 'Toscana', 'Pistoia'),
  (190, 'Ospedale di Livorno', 'Toscana', 'Livorno'),
  (191, 'Ospedale San Giuseppe', 'Lazio', 'Roma'),
  (192, 'Ospedale Sant%sAndrea', 'Lazio', 'Roma'),
  (193, 'Ospedale San Giovanni Calibita Fatebenefratelli', 'Lazio', 'Roma'),
  (194, 'Ospedale San Giovanni Addolorata', 'Lazio', 'Roma'),
  (195, 'Ospedale San Carlo di Nancy', 'Lazio', 'Rome'),
  (196, 'Ospedale Generale Provinciale Santa Maria della Misericordia', 'Toscana', 'Firenze'),
  (197, 'Ospedale Pediatrico Meyer', 'Toscana', 'Firenze'),
  (198, 'Ospedale San Jacopo', 'Toscana', 'Pistoia'),
  (199, 'Ospedale Santa Maria Nuova', 'Toscana', 'Firenze'),
  (200, 'Ospedale Santa Maria della Misericordia', 'Umbria', 'Perugia');

